### ISSUE TITLE
BasicTracerProvider vs NodeTracerProvider?

### ISSUE THREAD

**Issue by voxpelli** [autotelic/fastify-opentelemetry#8]
The example for this plugin uses `BasicTracerProvider` rather than `NodeTracerProvider` – is there a specific reason for this and is `NodeTracerProvider` equally supported as `BasicTracerProvider`?

(I'm very new to OpenTelemetry so this might very well be a very stupid question, apologizes in advance if that's the case)

**Comment by HW13** [comment]
No worries @voxpelli, no such thing as a stupid question 😄 .

The example is intended to be fairly simple, and that's why the `BasicTracerProvider` is used. The `NodeTracerProvider` provides features that, in the context of the example, aren't exactly necessary - these features being the inclusion of a default context manager and the addition of plugins (no relation to Fastify plugins). At its core, the `NodeTracerProvider` actually extends the `BasicTracerProvider`. 

To answer your question, yes it is equally supported - all tracer providers conforming to the OpenTelemetry API are supported by this module.

**Comment by voxpelli** [comment]
Thanks @HW13, that answers it for me 🙂
